In [1]:
#3.2.1 - load the ADP data file
# importing libraries
import pandas as pd
import numpy as np
from os import path

# File path
dataDir = '/Users/simmsjn/Documents/Github/ltcwff-files/data'

# DataFrame
pg = pd.read_csv(path.join(dataDir, 'player_game_2017_sample.csv'))

In [2]:
pg.head()

,player_name,week,carries,gameid,player_id,rush_yards,rush_fumbles,rush_tds,raw_yac,rec_fumbles,...,timeshit,interceptions,pass_tds,air_tds,season,team,pos,rec_yards,receptions,targets
0,T.Brady,1,0.0,2017090700,00-0019596,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,2017,NE,QB,0.0,0.0,0.0
1,A.Smith,1,2.0,2017090700,00-0023436,9.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,1.0,2017,KC,QB,0.0,0.0,0.0
2,D.Amendola,1,0.0,2017090700,00-0026035,0.0,0.0,0.0,49.0,1.0,...,0.0,0.0,0.0,0.0,2017,NE,WR,100.0,6.0,7.0
3,R.Burkhead,1,3.0,2017090700,00-0030288,15.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,2017,NE,RB,8.0,1.0,3.0
4,T.Kelce,1,1.0,2017090700,00-0030506,4.0,0.0,0.0,23.0,0.0,...,0.0,0.0,0.0,0.0,2017,KC,TE,40.0,5.0,7.0

#3.2.2  
Add a column to pg that gives the total rushing, rec, and passing yards for each player game
Do it two ways, on with basic arithmetic operators and another was using built-in pandas functions
call the columns 'total_yards1' and 'total_yards2'

In [5]:
# first way

pg['total_yards1'] = pg['rush_yards'] + pg['rec_yards'] + pg['pass_yards']
pg.head()

,player_name,week,carries,gameid,player_id,rush_yards,rush_fumbles,rush_tds,raw_yac,rec_fumbles,...,interceptions,pass_tds,air_tds,season,team,pos,rec_yards,receptions,targets,total_yards1
0,T.Brady,1,0.0,2017090700,00-0019596,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2017,NE,QB,0.0,0.0,0.0,267.0
1,A.Smith,1,2.0,2017090700,00-0023436,9.0,0.0,0.0,0.0,0.0,...,0.0,4.0,1.0,2017,KC,QB,0.0,0.0,0.0,377.0
2,D.Amendola,1,0.0,2017090700,00-0026035,0.0,0.0,0.0,49.0,1.0,...,0.0,0.0,0.0,2017,NE,WR,100.0,6.0,7.0,100.0
3,R.Burkhead,1,3.0,2017090700,00-0030288,15.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,2017,NE,RB,8.0,1.0,3.0,23.0
4,T.Kelce,1,1.0,2017090700,00-0030506,4.0,0.0,0.0,23.0,0.0,...,0.0,0.0,0.0,2017,KC,TE,40.0,5.0,7.0,44.0

In [9]:
# Second way
pg['total_yards2'] = pg[['rush_yards','pass_yards','rec_yards']].sum(axis = 1)
pg.head()

,player_name,week,carries,gameid,player_id,rush_yards,rush_fumbles,rush_tds,raw_yac,rec_fumbles,...,pass_tds,air_tds,season,team,pos,rec_yards,receptions,targets,total_yards1,total_yards2
0,T.Brady,1,0.0,2017090700,00-0019596,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2017,NE,QB,0.0,0.0,0.0,267.0,267.0
1,A.Smith,1,2.0,2017090700,00-0023436,9.0,0.0,0.0,0.0,0.0,...,4.0,1.0,2017,KC,QB,0.0,0.0,0.0,377.0,377.0
2,D.Amendola,1,0.0,2017090700,00-0026035,0.0,0.0,0.0,49.0,1.0,...,0.0,0.0,2017,NE,WR,100.0,6.0,7.0,100.0,100.0
3,R.Burkhead,1,3.0,2017090700,00-0030288,15.0,0.0,0.0,7.0,0.0,...,0.0,0.0,2017,NE,RB,8.0,1.0,3.0,23.0,23.0
4,T.Kelce,1,1.0,2017090700,00-0030506,4.0,0.0,0.0,23.0,0.0,...,0.0,0.0,2017,KC,TE,40.0,5.0,7.0,44.0,44.0

#### 3.2.3

In [11]:
pg.columns

Index(['player_name', 'week', 'carries', 'gameid', 'player_id', 'rush_yards',
       'rush_fumbles', 'rush_tds', 'raw_yac', 'rec_fumbles', 'rec_tds',
       'ac_tds', 'rec_raw_airyards', 'caught_airyards', 'attempts',
       'completions', 'pass_yards', 'pass_raw_airyards', 'comp_airyards',
       'timeshit', 'interceptions', 'pass_tds', 'air_tds', 'season', 'team',
       'pos', 'rec_yards', 'receptions', 'targets', 'total_yards1',
       'total_yards2'],
      dtype='object')

In [10]:
# A) What were the average vals for rushing and rec yards?

pg[['rush_yards','rec_yards']].mean()

rush_yards    14.909154
rec_yards     32.761705
dtype: float64

In [16]:
# B) How many times in our data did someone throw for over at least 300 AND at least 3 tds?

((pg['pass_yards'] >= 300) & (pg['pass_tds'] >= 3)).sum()

15

In [22]:
# C) What % of qb performances was that?
(((pg['pass_yards'] >= 300) & (pg['pass_tds'] >= 3)).sum()
 / (pg['pos'] == 'QB').sum())

0.10204081632653061

In [24]:
# D) How many rushings tds were there total in our sample

pg['rush_tds'].sum()

141.0

In [31]:
# E) What week is most represented in out sample? least?

pg['week'].value_counts()

# 14 and 8

14    92
4     91
13    89
12    89
3     89
2     86
7     86
10    85
11    84
5     84
15    82
16    82
17    79
9     79
6     79
1     79
8     76
Name: week, dtype: int64